# docker-compose.yml
version: '3.8'

services:
  server:
    build:
      context: ./server-app
    ports:
      - '8080:8080'
    restart: always

  client:
    build:
      context: ./front-app
    ports:
      - '3000:3000'
    restart: always
